-- MySQL Script generated by MySQL Workbench
-- Fri Aug  5 11:35:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(15) NOT NULL,
  `fullName` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missing` (
  `idmissing` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  `BirthPlace` VARCHAR(45) NOT NULL,
  `ageOfMissing` INT NOT NULL,
  `Sexe` VARCHAR(45) NOT NULL,
  `currentAdress` VARCHAR(255) NOT NULL,
  `previousAdress` VARCHAR(255) NULL,
  `city` VARCHAR(45) NOT NULL,
  `wilaya` VARCHAR(45) NOT NULL,
  `cityOfMissing` VARCHAR(45) NOT NULL,
  `wilayaOfMissing` VARCHAR(45) NOT NULL,
  `dateOfMissing` DATE NOT NULL,
  `phone` INT NULL,
  `height` INT NULL,
  `weight` INT NULL,
  `hair` VARCHAR(45) NULL,
  `eyes` VARCHAR(45) NULL,
  `photo` VARCHAR(255) NOT NULL,
  `blood` VARCHAR(45) NULL,
  `bloodPressure` TINYINT NULL,
  `diabet` TINYINT NULL,
  `mentalIlness` TINYINT NULL,
  `tatoos` TINYINT NULL,
  `birthmarks` TINYINT NULL,
  `scars` TINYINT NULL,
  `describing` LONGTEXT NULL,
  `isActive` TINYINT NOT NULL DEFAULT 0,
  `isFind` TINYINT NOT NULL DEFAULT 0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`idmissing`),
  INDEX `fk_missing_user_idx` (`user_iduser` ASC),
  UNIQUE INDEX `idmissing_UNIQUE` (`idmissing` ASC),
  CONSTRAINT `fk_missing_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
